/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HeroRouteImport } from './routes/hero'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTermsRouteImport } from './routes/_app.terms'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppOverviewRouteImport } from './routes/_app.overview'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAuditLogsRouteImport } from './routes/_app.audit-logs'
import { Route as AppTablesVariantsRouteImport } from './routes/_app.tables.variants'
import { Route as AppTablesStatesRouteImport } from './routes/_app.tables.states'
import { Route as AppTablesServersRouteImport } from './routes/_app.tables.servers'
import { Route as AppTablesRegionsRouteImport } from './routes/_app.tables.regions'
import { Route as AppTablesProjectsRouteImport } from './routes/_app.tables.projects'
import { Route as AppTablesPersonnelRouteImport } from './routes/_app.tables.personnel'
import { Route as AppTablesCustomersRouteImport } from './routes/_app.tables.customers'

const HeroRoute = HeroRouteImport.update({
  id: '/hero',
  path: '/hero',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTermsRoute = AppTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppOverviewRoute = AppOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditLogsRoute = AppAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AppRoute,
} as any)
const AppTablesVariantsRoute = AppTablesVariantsRouteImport.update({
  id: '/tables/variants',
  path: '/tables/variants',
  getParentRoute: () => AppRoute,
} as any)
const AppTablesStatesRoute = AppTablesStatesRouteImport.update({
  id: '/tables/states',
  path: '/tables/states',
  getParentRoute: () => AppRoute,
} as any)
const AppTablesServersRoute = AppTablesServersRouteImport.update({
  id: '/tables/servers',
  path: '/tables/servers',
  getParentRoute: () => AppRoute,
} as any)
const AppTablesRegionsRoute = AppTablesRegionsRouteImport.update({
  id: '/tables/regions',
  path: '/tables/regions',
  getParentRoute: () => AppRoute,
} as any)
const AppTablesProjectsRoute = AppTablesProjectsRouteImport.update({
  id: '/tables/projects',
  path: '/tables/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppTablesPersonnelRoute = AppTablesPersonnelRouteImport.update({
  id: '/tables/personnel',
  path: '/tables/personnel',
  getParentRoute: () => AppRoute,
} as any)
const AppTablesCustomersRoute = AppTablesCustomersRouteImport.update({
  id: '/tables/customers',
  path: '/tables/customers',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hero': typeof HeroRoute
  '/audit-logs': typeof AppAuditLogsRoute
  '/dashboard': typeof AppDashboardRoute
  '/notifications': typeof AppNotificationsRoute
  '/overview': typeof AppOverviewRoute
  '/profile': typeof AppProfileRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/terms': typeof AppTermsRoute
  '/tables/customers': typeof AppTablesCustomersRoute
  '/tables/personnel': typeof AppTablesPersonnelRoute
  '/tables/projects': typeof AppTablesProjectsRoute
  '/tables/regions': typeof AppTablesRegionsRoute
  '/tables/servers': typeof AppTablesServersRoute
  '/tables/states': typeof AppTablesStatesRoute
  '/tables/variants': typeof AppTablesVariantsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hero': typeof HeroRoute
  '/audit-logs': typeof AppAuditLogsRoute
  '/dashboard': typeof AppDashboardRoute
  '/notifications': typeof AppNotificationsRoute
  '/overview': typeof AppOverviewRoute
  '/profile': typeof AppProfileRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/terms': typeof AppTermsRoute
  '/tables/customers': typeof AppTablesCustomersRoute
  '/tables/personnel': typeof AppTablesPersonnelRoute
  '/tables/projects': typeof AppTablesProjectsRoute
  '/tables/regions': typeof AppTablesRegionsRoute
  '/tables/servers': typeof AppTablesServersRoute
  '/tables/states': typeof AppTablesStatesRoute
  '/tables/variants': typeof AppTablesVariantsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/hero': typeof HeroRoute
  '/_app/audit-logs': typeof AppAuditLogsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/overview': typeof AppOverviewRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/terms': typeof AppTermsRoute
  '/_app/tables/customers': typeof AppTablesCustomersRoute
  '/_app/tables/personnel': typeof AppTablesPersonnelRoute
  '/_app/tables/projects': typeof AppTablesProjectsRoute
  '/_app/tables/regions': typeof AppTablesRegionsRoute
  '/_app/tables/servers': typeof AppTablesServersRoute
  '/_app/tables/states': typeof AppTablesStatesRoute
  '/_app/tables/variants': typeof AppTablesVariantsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hero'
    | '/audit-logs'
    | '/dashboard'
    | '/notifications'
    | '/overview'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/terms'
    | '/tables/customers'
    | '/tables/personnel'
    | '/tables/projects'
    | '/tables/regions'
    | '/tables/servers'
    | '/tables/states'
    | '/tables/variants'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/hero'
    | '/audit-logs'
    | '/dashboard'
    | '/notifications'
    | '/overview'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/terms'
    | '/tables/customers'
    | '/tables/personnel'
    | '/tables/projects'
    | '/tables/regions'
    | '/tables/servers'
    | '/tables/states'
    | '/tables/variants'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/hero'
    | '/_app/audit-logs'
    | '/_app/dashboard'
    | '/_app/notifications'
    | '/_app/overview'
    | '/_app/profile'
    | '/_app/reports'
    | '/_app/settings'
    | '/_app/terms'
    | '/_app/tables/customers'
    | '/_app/tables/personnel'
    | '/_app/tables/projects'
    | '/_app/tables/regions'
    | '/_app/tables/servers'
    | '/_app/tables/states'
    | '/_app/tables/variants'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  HeroRoute: typeof HeroRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/hero': {
      id: '/hero'
      path: '/hero'
      fullPath: '/hero'
      preLoaderRoute: typeof HeroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/terms': {
      id: '/_app/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof AppTermsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/overview': {
      id: '/_app/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AppOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit-logs': {
      id: '/_app/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AppAuditLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tables/variants': {
      id: '/_app/tables/variants'
      path: '/tables/variants'
      fullPath: '/tables/variants'
      preLoaderRoute: typeof AppTablesVariantsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tables/states': {
      id: '/_app/tables/states'
      path: '/tables/states'
      fullPath: '/tables/states'
      preLoaderRoute: typeof AppTablesStatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tables/servers': {
      id: '/_app/tables/servers'
      path: '/tables/servers'
      fullPath: '/tables/servers'
      preLoaderRoute: typeof AppTablesServersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tables/regions': {
      id: '/_app/tables/regions'
      path: '/tables/regions'
      fullPath: '/tables/regions'
      preLoaderRoute: typeof AppTablesRegionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tables/projects': {
      id: '/_app/tables/projects'
      path: '/tables/projects'
      fullPath: '/tables/projects'
      preLoaderRoute: typeof AppTablesProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tables/personnel': {
      id: '/_app/tables/personnel'
      path: '/tables/personnel'
      fullPath: '/tables/personnel'
      preLoaderRoute: typeof AppTablesPersonnelRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tables/customers': {
      id: '/_app/tables/customers'
      path: '/tables/customers'
      fullPath: '/tables/customers'
      preLoaderRoute: typeof AppTablesCustomersRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAuditLogsRoute: typeof AppAuditLogsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppOverviewRoute: typeof AppOverviewRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTermsRoute: typeof AppTermsRoute
  AppTablesCustomersRoute: typeof AppTablesCustomersRoute
  AppTablesPersonnelRoute: typeof AppTablesPersonnelRoute
  AppTablesProjectsRoute: typeof AppTablesProjectsRoute
  AppTablesRegionsRoute: typeof AppTablesRegionsRoute
  AppTablesServersRoute: typeof AppTablesServersRoute
  AppTablesStatesRoute: typeof AppTablesStatesRoute
  AppTablesVariantsRoute: typeof AppTablesVariantsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAuditLogsRoute: AppAuditLogsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppOverviewRoute: AppOverviewRoute,
  AppProfileRoute: AppProfileRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTermsRoute: AppTermsRoute,
  AppTablesCustomersRoute: AppTablesCustomersRoute,
  AppTablesPersonnelRoute: AppTablesPersonnelRoute,
  AppTablesProjectsRoute: AppTablesProjectsRoute,
  AppTablesRegionsRoute: AppTablesRegionsRoute,
  AppTablesServersRoute: AppTablesServersRoute,
  AppTablesStatesRoute: AppTablesStatesRoute,
  AppTablesVariantsRoute: AppTablesVariantsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  HeroRoute: HeroRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
